sudo: required
services: docker
before_install:
- docker build ./server -f ./server/Dockerfile.test -t nm/server-test
script:
- docker run -e USER_DATABASE -e JWT_SECRET -e EMAIL_DATABASE nm/server-test npm run
  test
after_success:
- docker build -t nm/client ./client
- docker build -t nm/server ./server
- docker build -t nm/nginx ./nginx
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker push nm/client
- docker push nm/server
- docker push nm/nginx
env:
  global:
  - secure: PN/6pmgz82cLtOybZLZOmBMJ/MYdUthq9CQzZm/TVgokZ1N18/Wtzv4UV9CaIxR75vUzGs6w/wAYz4QKM2brYZS8dRiYv1L50Hs1UuzEuXj3gaKwf/nhtmnKlt2WGZE4P7pBGlHbpKLH+gJu4zaowQIK2gGKfgz7302wE4VezJ7qX2CqepntfJXIWwykA/KnUTwzamKFbTTHBeHAX1U70K2bRUXJ02MvHEbo1zLjzKaByUUAQTlNksDidCmfD86s2QtzlAhuWaMAnklSFlK2n3K/UmhlWioEdT0+XnCe4E02W9dtMhUsgkvz1OQTqD6hnu2KYaegg1WMpqyplXBPkkoO0wAHoMl0eP5+27aQ/6s0+65Hki/tyIkODJ90OjVbmEuNnEMW/IfU4T066D9fKbOnqm7ie6YPCFwo0M0iiSe3ys+kgmCWigrB1gTy9VUwn/yzPhaez4mqwIL1wlLZmfnYNZHq9JjGyUc67CJKEe/ZJO8K62tpYNT0Hv0VllDrjhvp+pFUwkElP6x9oeam4QPEvK9jNpY60eNJjsMt7RaPUpdFx7VBh6g4KMXH7hj7IuMLcNhOS3de/NFGl3tVL9LOKxtVcm+ohCeiZorYkRAlYEZDz8r2dMxEpPJmEGBxrx894zRLQH4q17kFJhLBekbjflhQgw2YWyqeiZiLFjc=
  - secure: EG09UEVsH88lbTzh9D+c+QLZLP+k9jq4/CI3Jhwk86FLXUcYxu4Q6rHZS8+DhPSZq2cwQ3PnwQDJP2ThDN7Pg6ktcY548wRQQvRl/1vptXq5+pXRbz7xvkwzyGjkWs7sPkXQnjeTOxGuy6+wXaRalSslam4OinUGgfyehwTIklDX5Ilw01wtaZ99MEpiE5LwNgBvNNgXMpnVllwAnTh6IrlTmJbAa23tdQ88WgWRWcjNaosyuAYQaXMYGD4XjqXiFGdjevo5yzql8ov1A8CMtP3xwfTgr+17RXs4H5VrO2AEXInA1+zkn2FLPK2P8UDCGbk/z4nBo31EFJMXCBIYX9TWsTZKTX+vo4idNkMX3+oIoqAjt3kRIpOCGKjRlck6rl4aESKwrOlUGFMpNnAGoYOF5DsOo1CdNDbyd9RWI+ezDcURmvhL8bj31zdTmaScIokTusbjjMfdjvT93aW3mZRw7pFOSxy6F0tbOBLPdHZFvEFolUk/HOPjBqIPWmeDNdyFVV6jQ6lwNpTJ7Q/4b2uEAr8EHPue8HhNRQHug+BSXia8F8iYzQiczYVLWYDwzn69GxNFdRYIt88VB01wJcEz9e6govuz01EYPpYgmAT0J/75lWO1oXOgsk3NbnX7I1Okm7N+PW5jAU2we3V844kAnqMchnZr6I4H+btaK4I=
  - secure: MfxdFrWY8mdKeAfOUms9o+3vy/r8Ck+NiwOPVBj+78Q3vC8Zrw5+dY8d85/ZbRsX/DxTgs0UN7UH2OdrfMvvYAMccAO3gZc8ltKRpHyPD9OeY/G66vcb7s+Y46HDLEnBKa/GKCDTregA6JDMbCV1swPTzbnK37ZPfEnXn0M6OAHGK+J5u03VjQEnbVPEfEpTE6yedtv26MKKnsvlilaEcq/k+9T7ZjYQckqzOO0RdTYkn1sqB8f3aXI73uWJbny88kGEHuYWnTpYRtReR6+FaRIAz12Sh0bS1FnaOxtyAlyBAOm6Z+uu/SjhtG4S/s/1Ur4XeFWDlYxrY4ORhSRPG8S0GFcjJyvsrO0bPj1K7a8CBPF4bTkyoUbB106cruyCc8bPjVKg96WQXKjNRwgCoN5p6AUJ/JiAMhTBHOew1q5sE/scyNYh/BF2Zkkcz22HivzA8MVJHGweh4lL/L3qrJ9SYPWCPPY70fKgnTU9mnIZFzLKh7lEoGMK6zb/8sCy486NQjB28scS/GDc5YZWxyLSN8ivmO7quPHty0dO6kdn0kXrkmBnTs6cqI6E1xVUqzLZpWQ3MlxPTFp5eIA9dINVQ2ju9nLssB+kLvmZrbvUSfZsbOqKrT8d63FdXFH6n39WS9A77O/8Vd5qJr2YJ0cHv2q2+JTCcbEIZeYDEI0=
branches:
  only:
  - dev
deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: PostQL
  env: email
  bucket_name: elasticbeanstalk-us-east-1-461955714824
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"