sudo: required
services: docker
before_install:
- docker build ./server -f ./server/Dockerfile.test -t nm/server-test
script:
- docker run -e USER_DATABASE -e JWT_SECRET -e EMAIL_DATABASE nm/server-test npm run
  test
after_success:
- docker build -t nm/client ./client
- docker build -t nm/server ./server
- docker build -t nm/nginx ./nginx
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker push nm/client
- docker push nm/server
- docker push nm/nginx
env:
  global:
  - secure: PM5hlGPtDi1FKzahT1dsgeHaKMopFrA5RRjjRv+CB1EpfcrfhqVd6brIRY3L/IDw2r3Sq7A8yTeMCG8eUPB/mIJcv6MvMEPqVR6tqekTdNOaPO/iWONZA2F4gfvviBie9hz9YHm55C+Lj7TtGoZj0ZgmSstBumd7s2ieEeGjhhxoYbeLKc4bK1mHaIYTU+ckzFwazXDsiZDX1cZoM2to9vi+2XD0xxIkByGsXi10LQYuwPC2SlsgqbkZikjN5BfughLZ+jNPWXSnZEAwlcgrUyzLgpyVKf9YjbuHHOeXp7HEvlHyvdENesTgsPITR1syLQwjjLJMsDMdvWUb1//CFQ4R2oJWtZnIg7U/Tu+fAp7xwRTs7UL3xOSbQZBcyy5Pntgjcwf902H9Dihr2iLKt6KBicKjl0SxN8paf0qc/AeHEOhdc37ZOdf64XdcLTBcvpPUNvZgzldE61M/W5AZovJTrbtHucBAp/m2cwKPhTm8AVUk5Yd6F2cJVjZnbq2iqGxGl9D+p4hF+lqApMQezGtyQM958cUFRdvf62kqxLgh8nOL+znNBsuqbQ+mQqdWe/BSUFuXLiGA//1d2Q6+Niqig2c3j2dGH81j8ZJGFpaCvhruegyHr1dzJBmfGP+jurl8JdBqVIxBDq2MqOx9CHImulMbFA/TFGirQqAxXLY=
  - secure: ka8FQJ9LrIgSb51PbytvLOwMiY6x9zCbgM88/OLaDxuZMAJ0NqisvFgFCRF8bzklkdIJ/kI42u1lMIfrz3HDzIdUz+6kh7+exNOYzIc+0q9GOkVP73ocSzxeP2Tcoem4ZOmfapWysVTM01zymFMdhYiLNOvZ5mRHgW4cckbmMp0jxm5uu+eQr8xrQFniobaLuc34ECxL3Uu1PtBEPIlnRQVv7ioLaGegMUCkYjUzCIV2Il6q9ERJu8y2ZYHXorYsLPjdaPGAXil37OXfUSbAxo+F5unG0oRFqRAMOqfr5LAxh4rRSAbV+eJuF1H4Vis1w3LrGHTPu9l2p0+B3sTvHEoTRtDBESsjrNNB+6mGoi9EPJc/eMu/1SsIdkvQlgGJqoS+yJFHGyaKWwuw+FINgpdAO4uXCd7bjcSdj20/7JeFz6OHMQ8ZVbVp303IxtUfFS/Oa31HulSs2slpDEd0QGP9dhY6EU/a/iG234nQhlQtQwnDRg+CUCqHdoH0QAwen0ML9UzNEQTAlVsQ7zs3zQ6WUViGfER86Lmxi+YQWgc+2TX60CHcwQ61PtSFfvZ8KEBscNGDRE3/CQ/hWLDDAPtlfPbm0mdhZ9f/bKooUcxZcUn/o1eF2ndz8ugHh1DgHsmzYcmgcfxIonVnCKadiWxn5TsM2jdp3Lg/ZgUMBa8=
  - secure: PuARx4WzbJsoKULor8ezw2hLMVrKVe8qDaX4pqiUuUuyyIIr8iEa74oz4xBWKslf9k2sSUG7+jFUYPOWGHzSkpSxrsPO8estJbUGnMoMmURPFCFjExClklXqyoaW3m50RCYIQAgb8XKowrIOmIKa66ZhGZv1s0lYgo3gWVn5A8ytFzj3E7rfJlKAqpSxeroz0scvWWAsQtcyH9kk+pBmlPFqpcmIW6+CPLzZ8djCI0s3s1nb3Wy38n4N361ry/zC7j/733jAa0kiaY8saUCUpbAKHX8floHzDsU+jCseiCFylYB3Og5QtFfL6zm07PyqJbedFOmry9myyDdOzs158SIhIQsDRSm1kpVuWqgkIDm2030mUo/Xry3X6udhP5i9HpVqJ/1GBQ1lUFrJiE5BLqBDKPKnnSJLhR6jXNMyOuwhhPFpNqSl2afqc+CV0AQHxoFYc4tmPj61hwoDlb8hQV33YEKrhVV3as3K97k00b1uAM9x85bcATSYwDjUq9N/1DJQKo+qEMw7iotchgdkWqg5X/yHDPIPpa0j4zmtGmKbpCTfZvLa5dHeOLa6rIaIb8Vtl+6ZBrVTqp9JyLZWIZnrrF5Hxnriq1M+o0uPCzmMPHlwLTOwyG5TaSKXC6xuMe/8qjcp+1dE7jDZRAUDbnaBoZ8CBuzt2t+oHgre7Us=
branches:
  only:
  - dev
deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: PostQL
  env: email
  bucket_name: elasticbeanstalk-us-east-1-461955714824
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
