export const FETCH_EMAILS_START = 'FETCH_EMAILS_START';
export const FETCH_EMAILS_PASS = 'FETCH_EMAILS_PASS';
export const FETCH_EMAILS_FAIL = 'FETCH_EMAILS_FAIL';

export const DELETE_EMAIL_START = 'DELETE_EMAIL_START';
export const DELETE_EMAIL_PASS = 'DELETE_EMAIL_PASS';
export const DELETE_EMAIL_FAIL = 'DELETE_EMAIL_FAIL';
