export const CHECK_COOKIES_START = 'CHECK_COOKIES_START';
export const CHECK_COOKIES_PASS = 'CHECK_COOKIES_PASS';
export const CHECK_COOKIES_FAIL = 'CHECK_COOKIES_FAIL';

// logout actions
export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_PASS = 'LOGOUT_PASS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
